name: class_clarity
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
      - google-api-python-client
      - google-auth-httplib2
      - google-auth-oauthlib
      - ollama
      - fastapi
      - uvicorn
      - streamlit
      - pydantic
      - requests